// <auto-generated />
namespace Framework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SeedUserData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedUserData));
        
        string IMigrationMetadata.Id
        {
            get { return "202405110000141_SeedUserData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
